### ISSUE TITLE
Disposed duplex stream should throw ObjectDisposedException on reading and writing.

### ISSUE THREAD

**Issue by IlyaBiryukov** [AArnott/Nerdbank.FullDuplexStream#1]
*Repro:*
1. Create a duplex stream pair
2. Dispose the streams
3. Try to read and write

*Expected:*
Once the stream is disposed, any operation on it should throw ObjectDisposedException

*Actual:*
The steam is still operational after disposal, reading and writing works as if the stream hasn't been disposed of.

**Comment by AArnott** [comment]
@IlyaBiryukov would you care to review the PR?
