### ISSUE TITLE
[Question] Stream not able to communicate across process unless use with other mechanism?

### ISSUE THREAD

**Issue by steamypassion** [AArnott/Nerdbank.FullDuplexStream#5]
Hi, If i have two separate application, build separately. It can communicate across process using Named Pipe and it seem to be quite good in cross platform support in .NET Core 2.0

If using Stream, what possible way to achieve two process communication to use with Stream? 
- Shared Memory to store the FullDuplexStream?
- etc...

**Comment by AArnott** [comment]
`FullDuplexStream` is designed to work within a single `AppDomain` and process. For inter-process communication, you should use pipes. .NET streams backed by pipes are similarly bidirectional. In fact FullDuplexStream was written to emulate the behavior of pipe streams, but without the native dependency.
